const List<String> bangaloreColleges = [
  'NMIT Bangalore',
  'RV College of Engineering',
  'BMS College of Engineering',
  'MS Ramaiah Institute of Technology',
  'PES University',
  'Dayananda Sagar College of Engineering',
  'Bangalore Institute of Technology',
  'New Horizon College of Engineering',
  'CMR Institute of Technology',
  'Sir M Visvesvaraya Institute of Technology',
  'Acharya Institute of Technology',
  'Jain University',
  'Presidency University',
  'Alliance University',
  'Christ University',
  'St Joseph’s College',
  'Mount Carmel College',
  'Reva University',
  'East Point College of Engineering',
  'Global Academy of Technology',
  'Don Bosco Institute of Technology',
  'Oxford College of Engineering',
  'AMC Engineering College',
  'BNM Institute of Technology',
  'RNS Institute of Technology',
  'Atria Institute of Technology',
  'KS Institute of Technology',
  'Brindavan College of Engineering',
  'HKBK College of Engineering',
  'SJB Institute of Technology',
  'MVJ College of Engineering',
  'Gopalan College of Engineering',
  'T John Institute of Technology',
  'Cambridge Institute of Technology',
  'Sapthagiri College of Engineering',
  'Vivekananda Institute of Technology',
  'Garden City University',
  'KNS Institute of Technology',
  'Kristu Jayanti College',
  'Bangalore University',
  'Indian Institute of Science (IISc)',
];