// File: lib/firebase_options.dart
// GENERATED BY FLUTTERFIRE CLI — DO NOT EDIT

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ================= ANDROID =================
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa2lnAm9eAzaSQqcHDyEQ3nzNW7UXxpLs',
    appId: '1:476600888374:android:cc1c467f003090d10dfc97',
    messagingSenderId: '476600888374',
    projectId: 'navdeep-college-app',
    storageBucket: 'navdeep-college-app.firebasestorage.app',
  );

  // ================= iOS =================
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBehc3TI_Wrg8P1_N2IQ0s2qMlyISiMj8M',
    appId: '1:476600888374:ios:9cbae2f22e0b90710dfc97',
    messagingSenderId: '476600888374',
    projectId: 'navdeep-college-app',
    storageBucket: 'navdeep-college-app.firebasestorage.app',
    iosBundleId: 'com.navdeep.collegeapp',
  );

  // ================= macOS =================
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBehc3TI_Wrg8P1_N2IQ0s2qMlyISiMj8M',
    appId: '1:476600888374:ios:9cbae2f22e0b90710dfc97',
    messagingSenderId: '476600888374',
    projectId: 'navdeep-college-app',
    storageBucket: 'navdeep-college-app.firebasestorage.app',
    iosBundleId: 'com.navdeep.collegeapp',
  );

  // ================= Windows =================
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDa2lnAm9eAzaSQqcHDyEQ3nzNW7UXxpLs',
    appId: '1:476600888374:web:placeholder',
    messagingSenderId: '476600888374',
    projectId: 'navdeep-college-app',
    storageBucket: 'navdeep-college-app.firebasestorage.app',
  );

  // ================= Web =================
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa2lnAm9eAzaSQqcHDyEQ3nzNW7UXxpLs',
    appId: '1:476600888374:web:placeholder',
    messagingSenderId: '476600888374',
    projectId: 'navdeep-college-app',
    storageBucket: 'navdeep-college-app.firebasestorage.app',
  );
}